### ISSUE TITLE
SPI out not working?

### ISSUE THREAD

**Issue by mccdam28** [elkayem/midi2cv#2] opened 2018-02-22 09:35 UTC
I've built this project but don't seem to get any SPI out, MIDI goes in, SPI does not come out. Tested the SPI out separately and that works fine. Anything i'm missing? @elkayem

**Comment by elkayem** [comment] 2018-03-09 22:54
Did you ever figure out this problem?  Several others have built this project with success, so I know the code works.  I know it can be difficult to debug without access to the serial lines, which are tied up for MIDI communication.  I often set up another arduino as an SPI slave using Nick Gammon's SPI Slave code, and output debugging messages over the serial port that way.  See his Master/Slave example about a third of the way down: http://www.gammon.com.au/spi

**Comment by mccdam28** [comment] 2018-03-10 15:51
will give this ago, it seems midi comes in but no SPI comes out. Will get back to it this weekend.

**Comment by CharlesV55** [comment] 2018-05-09 11:54
Hi, I'm experiencing the same issue on SPI Out. 
In the code, you didn't declare D13 & D11, connected to pin 3 & 4 of DAC's. Is it on purpose?

**Comment by elkayem** [comment] 2018-05-09 13:28
Pins 11 and 13 are the SPI MOSI and CLK for the nano and are already declared in the SPI library.  

A few questions...  have you looked at the SPI signals on a scope and confirmed they aren’t working?   Are your wires short?  Could the issue be with your midi in instead?   Have you disconnected from your computer when using?   

Let me know the results of your troubleshooting efforts.   Others have also successfully used this code, but it is always possible something changes in one of the libraries that breaks things.  

Larry

**Comment by CharlesV55** [comment] 2018-05-09 13:58
Hi, Larry,
Thanks for answering.
Stupid me, pin 11 & 13 are effectively used by SPI!
Unfortunately, there is no SPI-out on the scope, and no SPI-clock either.
I'm disconnected from computer, device is on a PCB, 10Volts powered,
in order to be used on my MiniMoog Model D.
Libraries size I use:
Midi.h > 109KB
SPI.h > 309KB
Perhaps a Library issue, as you mentionned?
My Arduino Nano is a Chinese one, worked fine 
with other Midi-to-something devices I made.
Regards 

----- Mail original -----
De: "Larry McGovern" <notifications@github.com>
À: "elkayem/midi2cv" <midi2cv@noreply.github.com>
Cc: "CharlesV55" <charles.rangheard@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Mercredi 9 Mai 2018 15:28:01
Objet: Re: [elkayem/midi2cv] SPI out not working? (#2)

Pins 11 and 13 are the SPI MOSI and CLK for the nano and are already declared in the SPI library. 

A few questions... have you looked at the SPI signals on a scope and confirmed they aren’t working? Are your wires short? Could the issue be with your midi in instead? Have you disconnected from your computer when using? 

Let me know the results of your troubleshooting efforts. Others have also successfully used this code, but it is always possible something changes in one of the libraries that breaks things. 

Larry

**Comment by elkayem** [comment] 2018-05-09 14:47
Is there anything on pin 2 coming from midi? Do the chip select pins 8 and 9 ever go low? It could be a problem with the midi signal, or the midi messages might not be interpreted correctly.   The midi library worked in my case but maybe something changed.  I’ve used a lot of Chinese nano clones and they either work completely or not at all.  

Larry

**Comment by CharlesV55** [comment] 2018-05-11 07:52
Hi,
Midi signal is present on N°2 Tx pin, the Led flashes,
and on the scope the signal goes correctly from +5V to 0V.
Pin 8 & 9 are High and never go low.
Is it supposed to generate a clock signal on pin 13?

I've used the same Midi-in circuit on several Midi-to-Yamaha
mixing consoles controls I made, no problem.
I use MidiOx to generate Midi notes on channel 1, already used
with other Midi interfaces to test them, no problem, so far.

I've ordered some other Arduino Nano clones on Ebay, perhaps
this will solve the issue, cross fingers!
By the way, congrat's for your job.


----- Mail original -----
De: "Larry McGovern" <notifications@github.com>
À: "elkayem/midi2cv" <midi2cv@noreply.github.com>
Cc: "CharlesV55" <charles.rangheard@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Mercredi 9 Mai 2018 16:47:58
Objet: Re: [elkayem/midi2cv] SPI out not working? (#2)

Is there anything on pin 2 coming from midi? Do the chip select pins 8 and 9 ever go low? It could be a problem with the midi signal, or the midi messages might not be interpreted correctly. The midi library worked in my case but maybe something changed. I’ve used a lot of Chinese nano clones and they either work completely or not at all. 

Larry

**Comment by CharlesV55** [comment] 2018-05-15 10:49
Hi, Larry,
I've found the problem:
The Tx signal must been pulled up to the +5V with a 1 KOhms resistance
instead of  512 Ohms, due to my 4N35 opto.
It works perfectly, now.
Thanks again.

**Comment by elkayem** [comment] 2018-05-26 22:40
I am going to close this issue, as I do not believe there is a problem with the SPI out in this code.  As CharlesV55 posted, check your optocoupler datasheet if you are using a different one that I have posted.  For example, the 4N35 optocoupler CharlesV55 used had a 30 - 40 usec high to low switch time when using a 500 ohm resistor, which is likely to slow for the 31.25 kbps MIDI rate (32 usec/bit).  Switching to a 1 k resistor reduced the switch time to 20 usec, which appears to be sufficient for his case.  Alternatively, the SFH618A optocoupler I use has < 10 usec switch time, and has not given me any problems with MIDI communication.

**Closed as completed by elkayem** 2018-05-26 22:40 UTC
